# Generated by Django 4.2 on 2023-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='number',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='passwords',
            name='password',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
