# Generated by Django 4.2 on 2023-05-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_orderitem'),
        ('order', '0004_alter_orderitem_options_alter_orderitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(related_name='product_order_items', to='products.product'),
        ),
    ]
