# Generated by Django 4.2 on 2023-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('rent', 'rent'), ('sale', 'sale')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
