# Generated by Django 4.2 on 2023-05-23 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
