# Generated by Django 4.2 on 2023-05-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_url',
            field=models.URLField(blank=True),
        ),
    ]
