# Generated by Django 4.2 on 2023-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_qr_code_product_qr_code_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qr_code_url',
            new_name='code_url',
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
