# Generated by Django 4.2 on 2023-10-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_qr_code_url_product_code_url_product_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_images',
        ),
    ]
