# Generated by Django 4.2 on 2023-04-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_bookproduct_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookproduct',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
    ]
